ALTER TYPE "SubmissionStatus" ADD VALUE IF NOT EXISTS 'MEMORY_LIMIT_EXCEEDED';
ALTER TYPE "SubmissionStatus" ADD VALUE IF NOT EXISTS 'COMPILATION_ERROR';
ALTER TYPE "SubmissionStatus" ADD VALUE IF NOT EXISTS 'SYSTEM_ERROR';

ALTER TABLE "Submission"
ADD COLUMN "judgeStatusRaw" TEXT,
ADD COLUMN "judgeCallbackPayload" JSONB,
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
