services:
  db:
    image: postgres:16
    container_name: judge-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: judge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wrdd
    volumes:
      - judge_db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro

volumes:
  judge_db_data:
